In [1]:
# Importing pandas and numpy
import pandas as pd
import numpy as np

In [2]:
# Reading the data set in using pandas
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/haberman/haberman.data',header=None)

In [3]:
# Assigning values of features and responses to X and y
X,y = df.values[:,:3] ,df.values[:, 3]
print (X)

[[30 64  1]
 [30 62  3]
 [30 65  0]
 [31 59  2]
 [31 65  4]
 [33 58 10]
 [33 60  0]
 [34 59  0]
 [34 66  9]
 [34 58 30]
 [34 60  1]
 [34 61 10]
 [34 67  7]
 [34 60  0]
 [35 64 13]
 [35 63  0]
 [36 60  1]
 [36 69  0]
 [37 60  0]
 [37 63  0]
 [37 58  0]
 [37 59  6]
 [37 60 15]
 [37 63  0]
 [38 69 21]
 [38 59  2]
 [38 60  0]
 [38 60  0]
 [38 62  3]
 [38 64  1]
 [38 66  0]
 [38 66 11]
 [38 60  1]
 [38 67  5]
 [39 66  0]
 [39 63  0]
 [39 67  0]
 [39 58  0]
 [39 59  2]
 [39 63  4]
 [40 58  2]
 [40 58  0]
 [40 65  0]
 [41 60 23]
 [41 64  0]
 [41 67  0]
 [41 58  0]
 [41 59  8]
 [41 59  0]
 [41 64  0]
 [41 69  8]
 [41 65  0]
 [41 65  0]
 [42 69  1]
 [42 59  0]
 [42 58  0]
 [42 60  1]
 [42 59  2]
 [42 61  4]
 [42 62 20]
 [42 65  0]
 [42 63  1]
 [43 58 52]
 [43 59  2]
 [43 64  0]
 [43 64  0]
 [43 63 14]
 [43 64  2]
 [43 64  3]
 [43 60  0]
 [43 63  2]
 [43 65  0]
 [43 66  4]
 [44 64  6]
 [44 58  9]
 [44 63 19]
 [44 61  0]
 [44 63  1]
 [44 61  0]
 [44 67 16]
 [45 65  6]
 [45 66  0]
 [45 67  1]
 [45

In [4]:
# Printing out the shape of X and y
print (X.shape)
print (y.shape)

(306, 3)
(306,)


In [5]:
# Importing metrics function
from sklearn import metrics


In [6]:
# Splitting data into training set and test set using size of 0.4 - 40% for testing, 60% for training.
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=4)
# Initializing Logisitic Regression algorithm using default parameters
logreg = LogisticRegression()
logreg.fit(X_train, y_train) # Fiting model with training data set

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [7]:
# Predicting on the test set using logistic regression
y_pred = logreg.predict(X_test)
#Comparing actual value response value(y_test) and predicted response value (y_pred)
print (metrics.accuracy_score(y_test, y_pred))

0.7804878048780488


In [8]:
# Making a confusion matrix using actual response and predicted response values
y = metrics.confusion_matrix(y_test, y_pred)

# Initliazing values from matrix to variables

#True Positive
TP = y[0,0] 
#False Negative 
FN = y[1,0]
# False Positive
FP = y[0,1]
#True Negative
TN = y[1,1]

#Printing out the Confusion Matrix
print (metrics.confusion_matrix(y_test, y_pred))

[[93  2]
 [25  3]]


In [9]:
# Working out the Accuracy Score
accuracy =  ((TN + TP)/(TN + FN + FP + TP))
# Working out the Error
error = 1 - accuracy
# Working out the True Positive Rate (Recall or Sensitivity)
true = TP/(TP + FN)
# Working out the False Positive Rate (Precision)
false = (TP/(FP + TP))

In [10]:
#Printing out the scores from above
print ("Accuracy Score:", accuracy)
print ("Error:", error)
print ("True Positive:", true)
print("False Positive:", false)

Accuracy Score: 0.7804878048780488
Error: 0.2195121951219512
True Positive: 0.788135593220339
False Positive: 0.9789473684210527
